export const ADD_LIST_ITEM = "ADD_LIST_ITEM";
export const UPDATE_LIST_ITEM = "UPDATE_LIST_ITEM";
export const REMOVE_LIST_ITEM = "REMOVE_LIST_ITEM";

export const SHOW_APP_NOTIFICATION = "SHOW_APP_NOTIFICATION";
export const HIDE_APP_NOTIFICATION = "HIDE_APP_NOTIFICATION";
