export const ADD_TRAIN = "ADD_TRAIN";
export const UPDATE_TRAIN = "UPDATE_TRAIN";
export const UPDATE_TRAIN_FILTER = "UPDATE_TRAIN_FILTER";
export const UPDATE_MAP_ZOOM = "UPDATE_MAP_ZOOM";
export const UPDATE_MAP_CENTER = "UPDATE_MAP_CENTER";
